version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

      # s> docker build -l test1         
      # bcdedit /set hypervisorlaunchtype auto
      # bcdedit /set hypervisorlauchtype auto